apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
  labels:
    app: myapp1
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb;

