apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3-prod
    spec:
      containers:
      - name: myapp3-container
        image: stacksimplifiy/kubenginx:3.0.0
        resources:
          limits:
            memory: "60Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
