apiVersion: v1
kind: Service
metadata:
  name: my-backend-service ##VERY IMPORTANT - NGINX PROXY-PASS needs this
  labels:
    app: backend-restapp
    tier: backend
spec:
  #type: ClusterIp is a default service
  selector:
    app: myapp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
