apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    name: curl-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - sleep
      - "600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
